### ISSUE TITLE
Issue with CPU usage

### ISSUE THREAD

**Issue by Silver-Crystal** [yofukashino/SystemRPC#1]
![image](https://github.com/user-attachments/assets/21d8aef4-28b4-4089-9539-e64f19fa2335)
![image](https://github.com/user-attachments/assets/07dccd10-1ef6-4953-bee6-e35fca33dd7f)
CPU usage is kind of messed up and way off for some reason

**Comment by yofukashino** [comment]
![image](https://github.com/user-attachments/assets/7b835387-6573-47c8-8abc-544aee69df1f)
shut up
